name: test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  macos:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - run: brew install libressl
    - run: xcrun swift test --enable-test-discovery --sanitize=thread -Xcxx "-I/usr/local/opt/openssl/include" -Xlinker "-L/usr/local/opt/openssl/lib"
  linux-4_2:
    runs-on: ubuntu-latest
    container:
       image: swift:4.2
    steps:
    - uses: actions/checkout@v2
    - run: swift test
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.2-focal
          - swift:5.3-focal
    container: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v2
    - run: apt-get -qq update && apt-get install -y libssl-dev
    - run: swift test --enable-test-discovery --sanitize=thread
